#!/usr/bin/env ruby

require 'yaml'
require 'watir-webdriver'

# variables
leitura_normal = ARGV[0]
leitura_bi = ARGV[1]
leitura_tri = ARGV[2]

# details
details = "#{ENV['HOME']}/.edp"

if File.exist?(details)
  edp_values = YAML.load_file(details)
else
  # create new file template
  out_file = File.new(details, 'w')
  out_file.puts(%(---
Nome:
Telefone:
Email:
Electricidade:
    CPE: # complete, without spaces
    Opcao Horaria: # 'simples', 'bi', 'tri'
Gas natural:
    CUI: # not yet working
    Leitura: # not yet working
...))
  out_file.close

  abort 'Foi criado um ficheiro em "~/.edp". Preenche-o com os dados necessários para começar a usar este script.'
end

# check hourly option
hourly_option = edp_values['Electricidade']['Opcao Horaria'].downcase[0]

if (hourly_option == 's') && ARGV[0].nil? || (hourly_option == 'b') && ARGV[1].nil? || (hourly_option == 't') && ARGV[2].nil?
  abort "instruções: #{$PROGRAM_NAME} <contagem_simples> <contagem_bi-horária> <contagem_tri-horária>" + "\n" * 2 + 'Precisas de dar o número de contagens referente ao tipo de horário.'
end

# start the browser, resize it (to use mobile version), and go to the page
browser = Watir::Browser.new :phantomjs
browser.goto 'https://energia.edp.pt/particulares/apoio-ao-cliente/envio-de-leituras.aspx'

# personal details
browser.text_field(name: 'Nome').set edp_values['Nome']
browser.text_field(name: 'Telemóvel').set edp_values['Telefone']
browser.text_field(name: 'Email').set edp_values['Email']
browser.text_field(name: 'cpe1').set edp_values['Electricidade']['CPE']

# counting details
browser.select(name: 'horario').select_value hourly_option # set hourly option

browser.text_field(name: 'NormalLeitura').set leitura_normal
browser.text_field(name: 'EconomicoLeitura').set leitura_bi if (hourly_option == 'b') || (hourly_option == 't')
browser.text_field(name: 'SuperEconomicoLeitura').set leitura_tri if (hourly_option == 't')

browser.link(class: 'send').click
browser.close
