#!/usr/bin/env ruby

require 'watir-webdriver'

# usage
if ARGV[0].nil?
  abort "instruções: olx-post <diretoria_com_imagens_e_info>

  A diretoria deve conter imagens em .jpg, e um ficheiro 'info.txt', com pelo menos três linhas
    - a primeira linha deverá ser o título do anúncio
    - a segunda o preço (sem símbolo de moeda)
    - todas as seguintes farão parte da descrição".gsub(%r{^ {2}},'')
end

# username and password
credentials = "#{ENV['HOME']}/.olx"

if File.exist?(credentials)
  username,password = File.read(credentials).split
else
  # if the credentials file does not exist, get info from arguments
  username = ARGV[1]
  password = ARGV[2]
end

# absolute path to the particular directory we want to act on
path = File.absolute_path(ARGV[0])

# file with information
# first line should be the title, second one the price, and all the subsequent ones will be part of the description
lines = File.readlines("#{path}/info.txt", :encoding => 'utf-8')
title = lines[0]
price = lines[1]
description = lines[2..-1]

# open browser and login
browser = Watir::Browser.new :chrome
browser.window.resize_to(1300, 700)
browser.goto "https://www.olx.pt/login/"
browser.text_field(:name => 'form[email]').set username
browser.text_field(:name => 'form[upw]').set password
browser.button(:name => 'login').click

# post new
browser.div(:id => 'create_adv_text').when_present.click

# set details
browser.text_field(:id => 'form_title').set title
browser.div(:class => 'suggestion').when_present.click
browser.text_field(:id => 'form_price').when_present.set price
browser.text_field(:id => 'form_desc').set description

# files to upload (filenames must end in .jpg)
num = 0
Dir.glob("#{path}/*.jpg") do |image|
  num += 1
  browser.file_field(:name => "file#{num}").set image
end

browser.select_list(:id => 'bbr_district').select 'Lisboa'
browser.select_list(:id => 'bbr_state').select 'Amadora'
browser.select_list(:id => 'bbr_town').select 'Mina'

browser.button(:value => 'Publicar Anúncio').click
browser.close
