#!/usr/bin/env ruby

# ensure watir-webdriver is installed
begin
  require 'watir-webdriver'
rescue Gem::LoadError
  puts 'watir-webdriver isn’t installed. Installing it now…'
  system('gem install watir-webdriver')
end

# username and password
credentials = "#{ENV['HOME']}/.config/olx"

if File.exist?(credentials)
  username, password = File.read(credentials).split
else
  # if the credentials file does not exist, get info from arguments
  username = ARGV[0]
  password = ARGV[1]
end

# start the browser and go to the page
browser = Watir::Browser.new :phantomjs
browser.goto 'https://olx.pt/account/'

# login
browser.text_field(id: 'userEmail').set username
browser.text_field(id: 'userPass').set password
browser.button(id: 'se_userLogin').click

# go to correct page
browser.goto 'http://olx.pt/myaccount/archive/'
browser.link(class: 'cookiesBarClose').click # needs to be closed, or will block other actions

while browser.exists?
  if browser.link(title: 'Activar anúncio').exists?
    browser.links(title: 'Activar anúncio').each(&:click)
    browser.refresh
  else
    browser.close
  end
end
