#!/usr/bin/env ruby

# ensure watir is installed
begin
  require 'watir'
rescue Gem::LoadError
  puts 'watir isn’t installed. Installing it now…'
  system('gem install watir')
end

# username and password
credentials = "#{ENV['HOME']}/.config/olx"

if File.exist?(credentials)
  username, password = File.read(credentials).split
else
  # if the credentials file does not exist, get info from arguments
  username = ARGV[0]
  password = ARGV[1]
end

# start the browser and go to the page
browser = Watir::Browser.new :chrome, switches: ['--headless']
browser.goto 'https://olx.pt/account/'

# login
browser.text_field(id: 'userEmail').set username
browser.text_field(id: 'userPass').set password
browser.button(id: 'se_userLogin').click
browser.button(id: 'se_userLogin').wait_while_present

# go to correct page
browser.goto 'https://olx.pt/myaccount/archive/'
browser.link(class: 'cookiesBarClose').click # needs to be closed, or will block other actions

loop do
  sleep 10 # with the new site implementation, there seems to be nothing we can reliably grab on to check if the page changed and loaded
  browser.links(class: 'activate-link activateOffer').each(&:click) if browser.link(class: 'activate-link activateOffer').exists?

  next_button = browser.span(class: 'fbold next abs large').link
  break unless next_button.exists?
  next_button.click
end

browser.close
