#!/usr/bin/env ruby

# ensure watir-webdriver is installed
begin
  require 'watir-webdriver'
rescue Gem::LoadError
  puts 'watir-webdriver isn’t installed. Installing it now…'
  system('gem install watir-webdriver')
end

require 'yaml'
require 'date'

# extend String to colorize messages
class String
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  def red
    colorize(31)
  end

  def green
    colorize(32)
  end
end

# usage
if ARGV[1].nil?
  abort "instruções: pedir-gas <daqui_a_quantos_dias_queres_a_entrega> <hora_da_entrega>"
end

# variables
delivery_days_from_today = ARGV[0].to_i
delivery_time = ARGV[1]

# delivery details
details = "#{ENV['HOME']}/.config/pontoazul"

if File.exist?(details)
  request = YAML.load_file(details)
else
  # create new file template
  out_file = File.new(details, 'w')
  out_file.puts(%(---
Primeiro nome:
Apelido:
Morada:
Código postal:
Localidade:
NIF:
Email:
Telefone:
Garrafas: # Deixar esta linha em branco, preencher as seguintes com quantidades
    Pluma 12kg:
    Butano 13kg:
    Propano 11kg:
    Propano 45kg:
...))
  out_file.close

  abort "Foi criado um ficheiro em '#{details}'. Preenche-o com os dados necessários para começar a usar este script."
end

# start the browser, resize it (to use mobile version), and go to the page
browser = Watir::Browser.new :phantomjs
browser.window.resize_to(1400, 900)
browser.goto 'http://pontoazul.com.pt/encomendas.php'

# fill details
postal_code = request['Código postal'].split('-')
delivery_date = (Date.today + delivery_days_from_today).strftime('%m/%d/%Y')

browser.text_field(id: 'Nome').set request['Primeiro nome']
browser.text_field(id: 'Apelido').set request['Apelido']
browser.text_field(id: 'Morada').set request['Morada']
browser.text_field(id: 'Codigo_Postal_1').set postal_code[0]
browser.text_field(id: 'Codigo_Postal').set postal_code[1]
browser.text_field(id: 'Localidade').set request['Localidade']
browser.text_field(id: 'NIF').set request['NIF']
browser.text_field(id: 'email').set request['Email']
browser.text_field(id: 'Telf').set request['Telefone']
browser.text_field(id: 'pluma12k').set request['Garrafas']['Pluma 12kg']
browser.text_field(id: 'butano13k').set request['Garrafas']['Butano 13kg']
browser.text_field(id: 'propano11k').set request['Garrafas']['Propano 11kg']
browser.text_field(id: 'propano45k').set request['Garrafas']['Propano 45kg']
browser.text_field(id: 'datepicker').set delivery_date
browser.text_field(id: 'horario').set delivery_time

browser.button(id: 'enviar').click
begin
  browser.div(text: /O seu pedido foi enviado com sucesso./).wait_until_present
rescue
  puts 'Houve um problema a enviar o pedido.'.red
  raise
else
  puts 'Pedido enviado com sucesso.'.green
end
browser.close
