#!/usr/bin/env ruby

# ensure watir-webdriver is installed
begin
  require 'watir-webdriver'
rescue Gem::LoadError
  puts 'watir-webdriver isn’t installed. Installing it now…'
  system('gem install watir-webdriver')
end

# username and password
credentials = "#{ENV['HOME']}/.readability"

if File.exist?(credentials)
  username,password = File.read(credentials).split
else
  # if the credentials file does not exist, get info from arguments
  username = ARGV[0]
  password = ARGV[1]
end

# start the browser, resize it (to use mobile version), and go to the page
browser = Watir::Browser.new :phantomjs
browser.window.resize_to(320, 700)
browser.goto 'https://readability.com/login/'

# login
browser.text_field(:id => 'username').set username
browser.text_field(:id => 'password').set password
browser.button(:value => 'Log In').click

# go to archives
browser.link(:class => 'toggle-nav-btn').when_present.click
browser.link(:class => 'nav-reading-list').when_present.click
browser.link(:class => 'icon-archive').when_present.click

# delete bookmarks
browser.div(:class => 'bookmark-search').wait_until_present
while browser.button(:class => 'item-controls-toggle').exists? do
  # number of archived links on page
  num = browser.buttons(:class => 'item-controls-toggle').size

  num.times do
    browser.button(:class => 'item-controls-toggle').click
    browser.button(:class => 'icon-delete').when_present.click
    sleep(1)
  end

  browser.refresh
end

browser.close
